---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['cpupower'] is defined"
    - "hostvars[inventory_hostname]['cpupower'] != ''"
    - "hostvars[inventory_hostname]['cpupower'] |
       community.general.json_query(vars['cpupower_install_package']) is
       defined"
    - "hostvars[inventory_hostname]['cpupower'] |
       community.general.json_query(vars['cpupower_install_package']) ==
       'true'"
  vars:
    cpupower_install_package: "[] | map(&install_package || 'false', @) | [0]"
- ansible.builtin.include_tasks:
    file: "deploy_cpupower.yml"
  when:
    - "vars['cpupower_settings'] is defined"
    - "vars['cpupower_settings'] != []"
