---
- name: cpupower | Install the required packages in Redhat derivatives
  yum:
    name: "{{ hostvars[inventory_hostname]['cpupower_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: cpupower | Install the required packages in Debian derivatives
  apt:
    name: "{{ hostvars[inventory_hostname]['cpupower_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: cpupower | Install the required packages in ArchLinux derivatives
  pacman:
    name: "{{ hostvars[inventory_hostname]['cpupower_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
  - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
